# Generated by Django 2.1.4 on 2019-01-19 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_faq_tos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request_Day_Off',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RequestDayOff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date_from', models.DateTimeField()),
                ('date_to', models.DateTimeField()),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'sickness'), (2, 'vacation'), (3, 'day off')], default=1)),
                ('reason', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Confirmed'), (2, 'Rejected')], default=0)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='sickness_days',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='vacation_days',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='requestdayoff',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dayoffs', to=settings.AUTH_USER_MODEL),
        ),
    ]
